### ISSUE TITLE
Unable to start jmeter-3.3 after putting pepper-box-1.0 jar

### ISSUE THREAD

**Issue by shahankit783** [GSLabDev/pepper-box#13]
Below is my environment :
1) Mac OS 
2) Apache 3.3
3) pepper-box 1.0 jar

After installing jar in jmeter plugin folder, I am getting error such as "An error occurred: Implementing class" + I am unable to find this plugin from Plugins manager . 

Please help me out asap. Thank you.

**Comment by Nachiket90** [comment]
Hi,

Error looks because of library conflicts. Plugins Manager generally do library version/conflict resolution and thus this issue won't occur. We are planning to add pepper-box to JMeter plugins and will be available soon. Solution to this is to manually check conflicting libraries (possibly guava) of other plugins you have installed with pepper-box and remove them if possible. 

Let us know if that helps.

**Comment by shahankit783** [comment]
Hi,

Thank you for reply. Can you please suggest the plugin versions of libraries (guava or any other dependancy) so that I can try at my end and we can resolve this issue.

**Comment by shahankit783** [comment]
I am putting in ext folder only .Path is "/apache-jmeter-3.3/lib/ext".

**Comment by satishbhor** [comment]
can u paste complete error ?

**Comment by shahankit783** [comment]
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/Users/ankit/apache-jmeter-3.3/lib/log4j-slf4j-impl-2.8.2.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/Users/ankit/apache-jmeter-3.3/lib/ext/pepper-box-1.0.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.apache.logging.slf4j.Log4jLoggerFactory]
================================================================================
Don't use GUI mode for load testing, only for Test creation and Test debugging !
For load testing, use NON GUI Mode:
   jmeter -n -t [jmx file] -l [results file] -e -o [Path to output folder]
& adapt Java Heap to your test requirements:
   Modify HEAP="-Xms512m -Xmx512m" in the JMeter batch file
================================================================================
An error occurred: Implementing class

**Comment by satishbhor** [comment]
Little curious  nothing apart from `An error occurred: Implementing class`?

**Comment by shahankit783** [comment]
Jmeter-3.3. as stated in question and jmeter works fine if I remove pepper-box.jar file

**Comment by satishbhor** [comment]
Can't reproduce issue at my end its working fine on my machine, Could u please download clean Jmeter and just try putting pepper-box jar check if it works fine?

**Comment by shahankit783** [comment]
Hi Satish,

I have freshly downloaded 3.0 jmeter version , and I went to "https://github.com/GSLabDev/pepper-box" and downloaded code and giving this command line mvn clean install -Djmeter.version=3.0 -Dkafka.version=0.9.0.1 as mentioned but getting following error.


[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.6.0:testCompile (default-testCompile) on project pepper-box: Compilation failure: Compilation failure: 
[ERROR] /Users/ankitshah/Downloads/pepper-box-master/src/test/java/com/gslab/pepper/test/PepperBoxSamplerTest.java:[66,21] incompatible types: kafka.utils.MockTime cannot be converted to org.apache.kafka.common.utils.Time
[ERROR] /Users/ankitshah/Downloads/pepper-box-master/src/test/java/com/gslab/pepper/test/PepperBoxSamplerTest.java:[67,54] incompatible types: org.apache.kafka.common.utils.Time cannot be converted to kafka.utils.Time
[ERROR] /Users/ankitshah/Downloads/pepper-box-master/src/test/java/com/gslab/pepper/test/PepperBoxLoadGenTest.java:[60,21] incompatible types: kafka.utils.MockTime cannot be converted to org.apache.kafka.common.utils.Time
[ERROR] /Users/ankitshah/Downloads/pepper-box-master/src/test/java/com/gslab/pepper/test/PepperBoxLoadGenTest.java:[61,54] incompatible types: org.apache.kafka.common.utils.Time cannot be converted to kafka.utils.Time

Can you please help me out.

**Comment by satishbhor** [comment]
pushed commit take latest from master try it

**Comment by shahankit783** [comment]
Now build is successful, generated jar file of 20Mb size and put it in apache-3.0/lib/ext/pepper-box.1.0.jar but getting below error:
2018/02/27 12:54:09 FATAL - jmeter.JMeter: An error occurred:  java.lang.IncompatibleClassChangeError: Implementing class
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at org.apache.jorphan.reflect.ClassFinder.isChildOf(ClassFinder.java:377)
	at org.apache.jorphan.reflect.ClassFinder.access$000(ClassFinder.java:47)
	at org.apache.jorphan.reflect.ClassFinder$ExtendsClassFilter.accept(ClassFinder.java:92)
	at org.apache.jorphan.reflect.ClassFinder.findClassesInOnePath(ClassFinder.java:441)
	at org.apache.jorphan.reflect.ClassFinder.findClasses(ClassFinder.java:289)
	at org.apache.jorphan.reflect.ClassFinder.findClassesThatExtend(ClassFinder.java:264)
	at org.apache.jmeter.gui.action.ActionRouter.populateCommandMap(ActionRouter.java:310)
	at org.apache.jmeter.JMeter.startGui(JMeter.java:323)
	at org.apache.jmeter.JMeter.start(JMeter.java:480)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.jmeter.NewDriver.main(NewDriver.java:259)

**Comment by satishbhor** [comment]
Which version of JDK ur using ? 
Oracle JDK or Open JDK ?

**Comment by shahankit783** [comment]
Any updates on issue? Is it mandatory to install openjdk ?

**Comment by Nachiket90** [comment]
Unfortunately we are not able provide solution as issue is not reproducible at our end (on mac as well). You can try openjdk or if possible try on windows/linux machine and share your findings.

**Comment by shahankit783** [comment]
I have installed now openjdk with java 1.9. and it started working . But when try to run jmeter script getting following error.

Feb 28, 2018 1:48:22 PM com.gslab.pepper.input.SchemaTranslator getPlainTextMsgIterator
SEVERE: Failed to compileSchemaClass class
java.lang.RuntimeException: java.lang.NullPointerException
	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.handleExceptions(JavacTaskImpl.java:158)
	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:96)
	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:90)
	at com.gslab.pepper.input.compile.InMemoryJavaCompiler.compileSchemaClass(InMemoryJavaCompiler.java:43)
	at com.gslab.pepper.input.SchemaTranslator.getPlainTextMsgIterator(SchemaTranslator.java:47)
	at com.gslab.pepper.input.SchemaProcessor.getPlainTextMessageIterator(SchemaProcessor.java:36)
	at com.gslab.pepper.loadgen.impl.PlaintTextLoadGenerator.<init>(PlaintTextLoadGenerator.java:34)
	at com.gslab.pepper.config.plaintext.PlainTextConfigElement.iterationStart(PlainTextConfigElement.java:53)
	at org.apache.jmeter.control.GenericController.fireIterationStart(GenericController.java:393)
	at org.apache.jmeter.control.GenericController.fireIterEvents(GenericController.java:385)
	at org.apache.jmeter.control.GenericController.next(GenericController.java:158)
	at org.apache.jmeter.control.LoopController.next(LoopController.java:128)
	at org.apache.jmeter.threads.AbstractThreadGroup.next(AbstractThreadGroup.java:87)
	at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:248)
	at java.base/java.lang.Thread.run(Thread.java:844)
Caused by: java.lang.NullPointerException
	at jdk.zipfs/jdk.nio.zipfs.JarFileSystem.getVersionMap(JarFileSystem.java:137)
	at jdk.zipfs/jdk.nio.zipfs.JarFileSystem.createVersionedLinks(JarFileSystem.java:112)
	at jdk.zipfs/jdk.nio.zipfs.JarFileSystem.<init>(JarFileSystem.java:85)
	at jdk.zipfs/jdk.nio.zipfs.ZipFileSystemProvider.newFileSystem(ZipFileSystemProvider.java:134)
	at jdk.compiler/com.sun.tools.javac.file.JavacFileManager$ArchiveContainer.<init>(JavacFileManager.java:517)
	at jdk.compiler/com.sun.tools.javac.file.JavacFileManager.getContainer(JavacFileManager.java:319)
	at jdk.compiler/com.sun.tools.javac.file.JavacFileManager.list(JavacFileManager.java:715)
	at java.compiler@9.0.4/javax.tools.ForwardingJavaFileManager.list(ForwardingJavaFileManager.java:77)
	at jdk.compiler/com.sun.tools.javac.api.ClientCodeWrapper$WrappedJavaFileManager.list(ClientCodeWrapper.java:232)
	at jdk.compiler/com.sun.tools.javac.code.ClassFinder.list(ClassFinder.java:722)
	at jdk.compiler/com.sun.tools.javac.code.ClassFinder.scanUserPaths(ClassFinder.java:648)
	at jdk.compiler/com.sun.tools.javac.code.ClassFinder.fillIn(ClassFinder.java:529)
	at jdk.compiler/com.sun.tools.javac.code.ClassFinder.complete(ClassFinder.java:293)
	at jdk.compiler/com.sun.tools.javac.code.Symtab.lambda$addRootPackageFor$7(Symtab.java:758)
	at jdk.compiler/com.sun.tools.javac.code.Symbol.complete(Symbol.java:633)
	at jdk.compiler/com.sun.tools.javac.comp.Enter.visitTopLevel(Enter.java:354)
	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCCompilationUnit.accept(JCTree.java:529)
	at jdk.compiler/com.sun.tools.javac.comp.Enter.classEnter(Enter.java:285)
	at jdk.compiler/com.sun.tools.javac.comp.Enter.classEnter(Enter.java:300)

Have any idea. how to resolve it. ?
