### ISSUE TITLE
Failed to send message. Kafka 1.0.0, Jmeter 3.0

### ISSUE THREAD

**Issue by aAndriiKucherenko** [GSLabDev/pepper-box#16]
Version: commit e66ece5cccb2dac9ff5486ac142df300d1e104de
Jmeter: 3.0
Kafka: 1.0.0
openjdk version "1.8.0_151"

Use "Pepper-Box PlainText Config" 
key: test
schema template: {"foo": "bar"}

Logs:
`2018/03/08 15:07:08 ERROR - com.gslab.pepper.sampler.PepperBoxKafkaSampler: Failed to send message java.lang.NullPointerException
	at com.gslab.pepper.sampler.PepperBoxKafkaSampler.runTest(PepperBoxKafkaSampler.java:179)
	at org.apache.jmeter.protocol.java.sampler.JavaSampler.sample(JavaSampler.java:196)
	at org.apache.jmeter.threads.JMeterThread.executeSamplePackage(JMeterThread.java:465)
	at org.apache.jmeter.threads.JMeterThread.processSampler(JMeterThread.java:410)
	at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:241)
	at java.lang.Thread.run(Thread.java:748)`

`2018/03/08 15:07:08 ERROR - jmeter.threads.JMeterThread: Error while processing sampler 'Java Request' : java.lang.NullPointerException
	at org.apache.jmeter.samplers.SampleResult.setResponseData(SampleResult.java:704)
	at com.gslab.pepper.sampler.PepperBoxKafkaSampler.runTest(PepperBoxKafkaSampler.java:185)
	at org.apache.jmeter.protocol.java.sampler.JavaSampler.sample(JavaSampler.java:196)
	at org.apache.jmeter.threads.JMeterThread.executeSamplePackage(JMeterThread.java:465)
	at org.apache.jmeter.threads.JMeterThread.processSampler(JMeterThread.java:410)
	at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:241)
	at java.lang.Thread.run(Thread.java:748)`

**In Kafka  receives "null" instead of {"foo": "bar"}**

Also if specify zookeeper:
`2018/03/08 15:43:01 ERROR - org.apache.zookeeper.ClientCnxn: Error while calling watcher  java.lang.NullPointerException
	at org.apache.zookeeper.ClientCnxn$EventThread.processEvent(ClientCnxn.java:522)
	at org.apache.zookeeper.ClientCnxn$EventThread.run(ClientCnxn.java:498)`

**Comment by aAndriiKucherenko** [comment]
My bad, "message.value.placeholder' was mismatched
