### ISSUE TITLE
Unable to compile for Windows 7, JMeter 3.3 and Kafka 0.11.0.0

### ISSUE THREAD

**Issue by yangzii0920** [GSLabDev/pepper-box#25]
1. System: Windows 7
2. JMeter version: 3.3
3. Kafka version: 0.11.0.1

Error log:
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.6.0:testCompile (default-testCompile) on project pepper-box: Compilation failure
[ERROR] /D:/pepper-box-master/src/test/java/com/gslab/pepper/test/PepperBoxConfigElementTest.java:[12,28] package net.didion.jwnl.data does not exist
```

Tried with Jmeter version 3.0 and Kafka 0,9.0.1 and it worked fine.

**Comment by yangzii0920** [comment]
Taking below actions solved my problem:

1. switch to branch: ''jmeter3.2_kafka0.11.0.0"
2. remove unused import such as `net.didion.jwnl.data.Exc` in all test classes since I could not include the dependency nor download it and it's not used
3. run `mvn clean install -Dkafka.version=0.11.0.0 -Djmeter.version=3.3 -DskipTests` since it will give `NullPointerException` when running test class

This way I can build source but not sure if there's impact on the performance.

After adding the jar to JMeter lib/ext and restart, I can see the plug-in items.

**Comment by satishbhor** [comment]
Hope you have pulled correct branch as we already have branch for Kafka 0.11 did you tried that?

**Comment by yangzii0920** [comment]
Yes I switched to "jmeter3.2_kafka0.11.0.0".

I was able to build and 2 .jar files were generated: pepper-box-1.0.jar and original-pepper-box-1.0.jar which were both copied under lib/ext of jmeter. But when I run the test plan, it threw error:
```
SEVERE: Failed to compileSchemaClass class
java.lang.NullPointerException
        at com.gslab.pepper.input.compile.InMemoryJavaCompiler.compileSchemaClass(InMemoryJavaCompiler.java:39)
        at com.gslab.pepper.input.SchemaTranslator.getPlainTextMsgIterator(SchemaTranslator.java:47)
        at com.gslab.pepper.input.SchemaProcessor.getPlainTextMessageIterator(SchemaProcessor.java:36)
        at com.gslab.pepper.loadgen.impl.PlaintTextLoadGenerator.<init>(PlaintTextLoadGenerator.java:34)
        at com.gslab.pepper.config.plaintext.PlainTextConfigElement.iterationStart(PlainTextConfigElement.java:53)
        at org.apache.jmeter.control.GenericController.fireIterationStart(GenericController.java:393)
        at org.apache.jmeter.control.GenericController.fireIterEvents(GenericController.java:385)
        at org.apache.jmeter.control.GenericController.next(GenericController.java:158)
        at org.apache.jmeter.control.LoopController.next(LoopController.java:123)
        at org.apache.jmeter.threads.AbstractThreadGroup.next(AbstractThreadGroup.java:87)
        at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:253)
        at java.lang.Thread.run(Unknown Source)
```

And here's JAVA_HOME, Java and Maven version:
```
$ echo $JAVA_HOME
C:\Program Files\Java\jdk1.8.0_121
```
```
$ java -version
java version "1.8.0_171"
Java(TM) SE Runtime Environment (build 1.8.0_171-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.171-b11, mixed mode)
```
```
$ mvn -version
Apache Maven 3.5.0 (ff8f5e7444045639af65f6095c62210b5713f426; 2017-04-03T15:39:06-04:00)
Maven home: C:\Program Files\apache-maven-3.5.0
Java version: 1.8.0_121, vendor: Oracle Corporation
Java home: C:\Program Files\Java\jdk1.8.0_121\jre
Default locale: en_US, platform encoding: Cp1252
OS name: "windows 7", version: "6.1", arch: "amd64", family: "windows"
```

I'm not sure if this is the cause but what I've read is that the exception happens when Java home is pointing to JRE not JDK. But actually my JAVA_HOME env var is set to JDK directory, and Maven will always look for JRE.

**Comment by satishbhor** [comment]
First You should not put both jar, remove jar containing name original second jmeter is picking jre instead of jdk, check your PATH variable should not contain jre path

**Comment by yangzii0920** [comment]
I removed original-pepper-box-1.0.jar, and make sure JRE is not in PATH var. In PATH variable, JAVA_HOME is pointing to JDK path, and you can see from Maven `Java home: C:\Program Files\Java\jdk1.8.0_121\jre`. 
The problem is, Maven picks up JRE automatically, because even if I delete the jre folder under JDK path, it will look for jre install path
