### ISSUE TITLE
ERROR - com.gslab.pepper.sampler.PepperBoxKafkaSampler: Failed to get broker information org.apache.zookeeper.KeeperException$NoNodeException: KeeperErrorCode = NoNode for /brokers/ids

### ISSUE THREAD

**Issue by userseljm999** [GSLabDev/pepper-box#26]
ERROR - jmeter.threads.JMeterThread: Error while processing sampler 'Java Request - Updated with Details' : org.apache.kafka.common.KafkaException: Failed to construct kafka producer

Caused by: org.apache.kafka.common.KafkaException: javax.security.auth.login.LoginException: Unable to obtain password from user
[Jmeter Kafka Pepperbox Sampler Error.docx](https://github.com/GSLabDev/pepper-box/files/2063755/Jmeter.Kafka.Pepperbox.Sampler.Error.docx)

**Comment by userseljm999** [comment]
Errro i'm getting is 2018/06/05 14:09:42 ERROR - com.gslab.pepper.sampler.PepperBoxKafkaSampler: Failed to get broker information org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss for /brokers/ids
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:99)
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:51)
	at org.apache.zookeeper.ZooKeeper.getChildren(ZooKeeper.java:1472)
	at org.apache.zookeeper.ZooKeeper.getChildren(ZooKeeper.java:1500)
	at com.gslab.pepper.sampler.PepperBoxKafkaSampler.getBrokerServers(PepperBoxKafkaSampler.java:169)
	at com.gslab.pepper.sampler.PepperBoxKafkaSampler.setupTest(PepperBoxKafkaSampler.java:89)
	at org.apache.jmeter.protocol.java.sampler.JavaSampler.sample(JavaSampler.java:188)
	at org.apache.jmeter.threads.JMeterThread.process_sampler(JMeterThread.java:434)
	at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:261)
	at java.lang.Thread.run(Thread.java:748)

2018/06/05 14:09:43 ERROR - jmeter.threads.JMeterThread: Error while processing sampler 'Java Request' : org.apache.kafka.common.KafkaException: Failed to construct kafka producer
	at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:321)
	at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:181)
	at com.gslab.pepper.sampler.PepperBoxKafkaSampler.setupTest(PepperBoxKafkaSampler.java:116)
	at org.apache.jmeter.protocol.java.sampler.JavaSampler.sample(JavaSampler.java:188)
	at org.apache.jmeter.threads.JMeterThread.process_sampler(JMeterThread.java:434)
	at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:261)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.kafka.common.KafkaException: javax.security.auth.login.LoginException: Unable to obtain password from user

	at org.apache.kafka.common.network.SaslChannelBuilder.configure(SaslChannelBuilder.java:74)
	at org.apache.kafka.common.network.ChannelBuilders.create(ChannelBuilders.java:60)
	at org.apache.kafka.clients.ClientUtils.createChannelBuilder(ClientUtils.java:79)
	at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:271)
	... 6 more
Caused by: javax.security.auth.login.LoginException: Unable to obtain password from user

	at com.sun.security.auth.module.Krb5LoginModule.promptForPass(Krb5LoginModule.java:897)
	at com.sun.security.auth.module.Krb5LoginModule.attemptAuthentication(Krb5LoginModule.java:760)
	at com.sun.security.auth.module.Krb5LoginModule.login(Krb5LoginModule.java:617)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at javax.security.auth.login.LoginContext.invoke(LoginContext.java:755)
	at javax.security.auth.login.LoginContext.access$000(LoginContext.java:195)
	at javax.security.auth.login.LoginContext$4.run(LoginContext.java:682)
	at javax.security.auth.login.LoginContext$4.run(LoginContext.java:680)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.login.LoginContext.invokePriv(LoginContext.java:680)
	at javax.security.auth.login.LoginContext.login(LoginContext.java:587)
	at org.apache.kafka.common.security.kerberos.Login.login(Login.java:298)
	at org.apache.kafka.common.security.kerberos.Login.<init>(Login.java:104)
	at org.apache.kafka.common.security.kerberos.LoginManager.<init>(LoginManager.java:44)
	at org.apache.kafka.common.security.kerberos.LoginManager.acquireLoginManager(LoginManager.java:85)
	at org.apache.kafka.common.network.SaslChannelBuilder.configure(SaslChannelBuilder.java:55)
	... 9 more

2018/06/05 14:09:43 DEBUG - jmeter.control.GenericController: Calling next on: org.apache.jmeter.control.LoopController 
2018/06/05 14:09:43 INFO  - jmeter.threads.JMeterThread: Thread is done: Thread Group 1-1 
2018/06/05 14:09:43 INFO  - jmeter.threads.JMeterThread: Thread finished: Thread Group 1-1 
2018/06/05 14:09:43 DEBUG - jmeter.threads.ThreadGroup: Ending thread Thread Group 1-1 
2018/06/05 14:09:43 INFO  - jmeter.engine.StandardJMeterEngine: Notifying test listeners of end of test 
2018/06/05 14:09:43 DEBUG - jmeter.protocol.java.sampler.JavaSampler: StandardJMeterEngine@5f2baf77-Java Request	testEnded 
2018/06/05 14:09:43 WARN  - jmeter.engine.StandardJMeterEngine: Error encountered during shutdown of org.apache.jmeter.protocol.java.sampler.JavaSampler@5f2baf77 java.lang.NullPointerException
	at com.gslab.pepper.sampler.PepperBoxKafkaSampler.teardownTest(PepperBoxKafkaSampler.java:155)
	at org.apache.jmeter.protocol.java.sampler.JavaSampler.testEnded(JavaSampler.java:287)
	at org.apache.jmeter.engine.StandardJMeterEngine.notifyTestListenersOfEnd(StandardJMeterEngine.java:226)
	at org.apache.jmeter.engine.StandardJMeterEngine.run(StandardJMeterEngine.java:448)
	at java.lang.Thread.run(Thread.java:748)
