### ISSUE TITLE
Looking for pepperbox jar file for Jmeter 2.13 and Kafka 0.10 version

### ISSUE THREAD

**Issue by userseljm999** [GSLabDev/pepper-box#28]
Looking for pepperbox jar file for Jmeter 2.13 and Kafka 0.10 version

**Comment by Nachiket90** [comment]
Hi @userseljm999,

Any specific reason behind using Jmeter 2.13 version? As its outdated and JMeter recommends to use 3+ version. We will keep pepperbox jar file for Jmeter 3+ versions at publicly accessible location and share the location details.

If you insist to use Jmeter 2.13 then you can build pepperbox from source,
 `mvn clean install -Djmeter.version=2.13 -Dkafka.version=0.10.0.0`

**Comment by userseljm999** [comment]
Hi Nachiket90....Current jar at https://github.com/raladev/load/tree/master/JARs is using which kafka version ?It is updated 3 days back pepper-box-1.0.jar

**Comment by Nachiket90** [comment]
Its using kafka 0.10.0.0 version but not sure its in sync with pepperbox. I would recommend to build your own jar from latest Pepperbox pull.

**Comment by userseljm999** [comment]
@Nachiket90  
No i guess it is using lower version this is line from log 
2018-06-06 14:20:28,052 INFO o.a.k.c.u.AppInfoParser: Kafka version : 0.9.0.1


Which build i need to get Master or  Jmeter3.2_kafka10.2 branch?
My Requirement now is get pepperbox jar file for Jmeter version =3.2 and Kafka version=0.10.2.1

**Comment by userseljm999** [comment]
@Nachiket90   I build new jar using Branch Jmeter3.2kafka10.2 and used new jar file

I'm getting below error

2018-06-07 16:52:50,172 WARN o.a.z.ClientCnxn: SASL configuration failed: javax.security.auth.login.LoginException: Unable to obtain password from user
 Will continue connection to Zookeeper server without SASL authentication, if Zookeeper server allows it.
2018-06-07 16:52:50,172 INFO o.a.z.ClientCnxn: Opening socket connection to server 165.237.41.4/165.237.41.4:2181
2018-06-07 16:52:50,172 ERROR o.a.z.ClientCnxn: Error while calling watcher 
java.lang.NullPointerException: null
	at org.apache.zookeeper.ClientCnxn$EventThread.processEvent(ClientCnxn.java:530) [pepper-box-1.0.jar:?]
	at org.apache.zookeeper.ClientCnxn$EventThread.run(ClientCnxn.java:505) [pepper-box-1.0.jar:?]
2018-06-07 16:52:50,234 INFO o.a.z.ClientCnxn: Socket connection established to 165.237.41.4/165.237.41.4:2181, initiating session
2018-06-07 16:52:50,297 INFO o.a.z.ClientCnxn: Session establishment complete on server 165.237.41.4/165.237.41.4:2181, sessionid = 0x163b76b818e02cd, negotiated timeout = 10000
2018-06-07 16:52:50,297 ERROR o.a.z.ClientCnxn: Error while calling watcher 
java.lang.NullPointerException: null
	at org.apache.zookeeper.ClientCnxn$EventThread.processEvent(ClientCnxn.java:530) [pepper-box-1.0.jar:?]
	at org.apache.zookeeper.ClientCnxn$EventThread.run(ClientCnxn.java:505) [pepper-box-1.0.jar:?]
2018-06-07 16:52:50,359 ERROR c.g.p.s.PepperBoxKafkaSampler: Failed to get broker information
org.apache.zookeeper.KeeperException$NoNodeException: KeeperErrorCode = NoNode for /brokers/ids
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:111) ~[pepper-box-1.0.jar:?]
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:51) ~[pepper-box-1.0.jar:?]
	at org.apache.zookeeper.ZooKeeper.getChildren(ZooKeeper.java:1532) ~[pepper-box-1.0.jar:?]
	at org.apache.zookeeper.ZooKeeper.getChildren(ZooKeeper.java:1560) ~[pepper-box-1.0.jar:?]
	at com.gslab.pepper.sampler.PepperBoxKafkaSampler.getBrokerServers(PepperBoxKafkaSampler.java:207) [pepper-box-1.0.jar:?]
	at com.gslab.pepper.sampler.PepperBoxKafkaSampler.setupTest(PepperBoxKafkaSampler.java:105) [pepper-box-1.0.jar:?]
	at org.apache.jmeter.protocol.java.sampler.JavaSampler.sample(JavaSampler.java:194) [ApacheJMeter_java.jar:3.2 r1790748]
	at org.apache.jmeter.threads.JMeterThread.executeSamplePackage(JMeterThread.java:491) [ApacheJMeter_core.jar:3.2 r1790748]
	at org.apache.jmeter.threads.JMeterThread.processSampler(JMeterThread.java:425) [ApacheJMeter_core.jar:3.2 r1790748]
	at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:254) [ApacheJMeter_core.jar:3.2 r1790748]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
2018-06-07 16:52:50,390 INFO o.a.k.c.p.ProducerConfig: ProducerConfig values: 
	acks = 1
	batch.size = 16384
	block.on.buffer.full = false
	bootstrap.servers = [165.237.41.4:6668, 165.237.41.5:6668, 165.237.41.6:6668, 165.237.41.7:6668, 165.237.41.8:6668]
	buffer.memory = 33554432
	client.id = 
	compression.type = none
	connections.max.idle.ms = 540000
	interceptor.classes = null
	key.serializer = class org.apache.kafka.common.serialization.StringSerializer
	linger.ms = 0
	max.block.ms = 60000
	max.in.flight.requests.per.connection = 5
	max.request.size = 1048576
	metadata.fetch.timeout.ms = 60000
	metadata.max.age.ms = 300000
	metric.reporters = []
	metrics.num.samples = 2
	metrics.sample.window.ms = 30000
	partitioner.class = class org.apache.kafka.clients.producer.internals.DefaultPartitioner
	receive.buffer.bytes = 32768
	reconnect.backoff.ms = 50
	request.timeout.ms = 30000
	retries = 0
	retry.backoff.ms = 100
	sasl.jaas.config = null
	sasl.kerberos.kinit.cmd = /usr/bin/kinit
	sasl.kerberos.min.time.before.relogin = 60000
	sasl.kerberos.service.name = vod-kafka
	sasl.kerberos.ticket.renew.jitter = 0.05
	sasl.kerberos.ticket.renew.window.factor = 0.8
	sasl.mechanism = GSSAPI
	security.protocol = SASL_SSL
	send.buffer.bytes = 131072
	ssl.cipher.suites = null
	ssl.enabled.protocols = [TLSv1.2, TLSv1.1, TLSv1]
	ssl.endpoint.identification.algorithm = null
	ssl.key.password = null
	ssl.keymanager.algorithm = SunX509
	ssl.keystore.location = null
	ssl.keystore.password = null
	ssl.keystore.type = JKS
	ssl.protocol = TLS
	ssl.provider = null
	ssl.secure.random.implementation = null
	ssl.trustmanager.algorithm = PKIX
	ssl.truststore.location = null
	ssl.truststore.password = null
	ssl.truststore.type = JKS
	timeout.ms = 30000
	value.serializer = class org.apache.kafka.common.serialization.StringSerializer

2018-06-07 16:52:50,406 INFO o.a.k.c.p.KafkaProducer: Closing the Kafka producer with timeoutMillis = 0 ms.
2018-06-07 16:52:50,406 ERROR o.a.j.t.JMeterThread: Error while processing sampler: 'Java Request'.
org.apache.kafka.common.KafkaException: Failed to construct kafka producer
	at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:342) ~[pepper-box-1.0.jar:?]
	at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:191) ~[pepper-box-1.0.jar:?]
	at com.gslab.pepper.sampler.PepperBoxKafkaSampler.setupTest(PepperBoxKafkaSampler.java:150) ~[pepper-box-1.0.jar:?]
	at org.apache.jmeter.protocol.java.sampler.JavaSampler.sample(JavaSampler.java:194) ~[ApacheJMeter_java.jar:3.2 r1790748]
	at org.apache.jmeter.threads.JMeterThread.executeSamplePackage(JMeterThread.java:491) ~[ApacheJMeter_core.jar:3.2 r1790748]
	at org.apache.jmeter.threads.JMeterThread.processSampler(JMeterThread.java:425) [ApacheJMeter_core.jar:3.2 r1790748]
	at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:254) [ApacheJMeter_core.jar:3.2 r1790748]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
Caused by: org.apache.kafka.common.KafkaException: javax.security.auth.login.LoginException: Unable to obtain password from user

	at org.apache.kafka.common.network.SaslChannelBuilder.configure(SaslChannelBuilder.java:94) ~[pepper-box-1.0.jar:?]
	at org.apache.kafka.common.network.ChannelBuilders.create(ChannelBuilders.java:93) ~[pepper-box-1.0.jar:?]
	at org.apache.kafka.common.network.ChannelBuilders.clientChannelBuilder(ChannelBuilders.java:51) ~[pepper-box-1.0.jar:?]
	at org.apache.kafka.clients.ClientUtils.createChannelBuilder(ClientUtils.java:84) ~[pepper-box-1.0.jar:?]
	at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:305) ~[pepper-box-1.0.jar:?]
	... 7 more
Caused by: javax.security.auth.login.LoginException: Unable to obtain password from user

	at com.sun.security.auth.module.Krb5LoginModule.promptForPass(Krb5LoginModule.java:897) ~[?:1.8.0_51]
	at com.sun.security.auth.module.Krb5LoginModule.attemptAuthentication(Krb5LoginModule.java:760) ~[?:1.8.0_51]
	at com.sun.security.auth.module.Krb5LoginModule.login(Krb5LoginModule.java:617) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at javax.security.auth.login.LoginContext.invoke(LoginContext.java:755) ~[?:1.8.0_51]
	at javax.security.auth.login.LoginContext.access$000(LoginContext.java:195) ~[?:1.8.0_51]
	at javax.security.auth.login.LoginContext$4.run(LoginContext.java:682) ~[?:1.8.0_51]
	at javax.security.auth.login.LoginContext$4.run(LoginContext.java:680) ~[?:1.8.0_51]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_51]
	at javax.security.auth.login.LoginContext.invokePriv(LoginContext.java:680) ~[?:1.8.0_51]
	at javax.security.auth.login.LoginContext.login(LoginContext.java:587) ~[?:1.8.0_51]
	at org.apache.kafka.common.security.authenticator.AbstractLogin.login(AbstractLogin.java:58) ~[pepper-box-1.0.jar:?]
	at org.apache.kafka.common.security.kerberos.KerberosLogin.login(KerberosLogin.java:109) ~[pepper-box-1.0.jar:?]
	at org.apache.kafka.common.security.authenticator.LoginManager.<init>(LoginManager.java:55) ~[pepper-box-1.0.jar:?]
	at org.apache.kafka.common.security.authenticator.LoginManager.acquireLoginManager(LoginManager.java:89) ~[pepper-box-1.0.jar:?]
	at org.apache.kafka.common.network.SaslChannelBuilder.configure(SaslChannelBuilder.java:86) ~[pepper-box-1.0.jar:?]
	at org.apache.kafka.common.network.ChannelBuilders.create(ChannelBuilders.java:93) ~[pepper-box-1.0.jar:?]
	at org.apache.kafka.common.network.ChannelBuilders.clientChannelBuilder(ChannelBuilders.java:51) ~[pepper-box-1.0.jar:?]
	at org.apache.kafka.clients.ClientUtils.createChannelBuilder(ClientUtils.java:84) ~[pepper-box-1.0.jar:?]
	at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:305) ~[pepper-box-1.0.jar:?]
	... 7 more
2018-06-07 16:52:50,406 INFO o.a.j.t.JMeterThread: Thread is done: Thread Group 1-1




****************
On Jmeter console  i see logs as 


================================================================================

Looking for keys for: svc-bd-sdpprstb-dev@DEVHADOOP.xxxxx.COM
Java config name: C:/Users/svc_automation/Desktop/KAFKA/apache-jmeter-3.2/bin/kr
b5.conf
Loaded from Java config
Looking for keys for: svc-bd-sdpprstb-dev@DEVHADOOP.xxxx.COM

**Comment by Nachiket90** [comment]
This is because of keytab file permissions. Please validate read permissions of keytab file and provide if already not available.
