### ISSUE TITLE
Getting KafkaProducer: Closing the Kafka producer with timeoutMillis = 9223372036854775807 ms in jmeter log

### ISSUE THREAD

**Issue by ShauryaSid** [GSLabDev/pepper-box#29]
Hi ,
I am new to Kafka but we have a requirement of performance testing for Kafka topic. I created Jmeter script using pepper box  Jar file batch - Jmeter3.2_10.2. **But we are getting "KafkaProducer: Closing the Kafka producer with timeoutMillis = 9223372036854775807 ms " info in Jmeter log file. and data is not inserting to the required topic.** Kindly let me know how can we resolve this issue. 
Other info:
Jmeter 3.2
Kafka 0.10.1.0
* Is kafka version difference ( 10.2 & 10.1) causing issue?
Thanks,

**Comment by Nachiket90** [comment]
Seems to be a connectivity/permissions issue. Can you check with console producer and consumer once and also validate you are able to connect to kafka brokers/zookeeper from JMeter node if running on different machine? 
If your cluster is kerberized then validate permissions like keytab and jaas file configs.

**Comment by ShauryaSid** [comment]
Hi, 
As i was running current script from EC2 instance it might be permission issue and it cannot be resolved since they are not agreed to add security group for this machine.
But now i tried from my local machine i am getting below error and some null pointer exceptions.
2018-06-11 15:33:41,090 ERROR c.g.p.l.i.PlaintTextLoadGenerator: Please make sure that expressions functions are already defined and parameters are correctly passed.
com.gslab.pepper.exception.PepperBoxException: java.lang.NullPointerException
	at com.gslab.pepper.input.SchemaTranslator.getPlainTextMsgIterator(SchemaTranslator.java:54) ~[pepper-box-1.0%20(2).jar:?]
	at com.gslab.pepper.input.SchemaProcessor.getPlainTextMessageIterator(SchemaProcessor.java:36) ~[pepper-box-1.0%20(2).jar:?]
	at com.gslab.pepper.loadgen.impl.PlaintTextLoadGenerator.<init>(PlaintTextLoadGenerator.java:34) [pepper-box-1.0%20(2).jar:?]
Kindly let me know the solution and further details if required.  However, these errors/ exceptions were not observed during running from EC2 instance.
Details:
Local machine details:
OS: Windows
JDK- 1.8

Thanks ,

**Comment by vikasrjain** [comment]
Hi 

We are gertting "KafkaProducer: Closing the Kafka producer with timeoutMillis = 9223372036854775807 ms" in jmeter log even running from my local machine.
Below are the details:

using SSL protocol from kafka connections
ssl.enabled	
ssl.key.password
ssl.keystore.location	
ssl.keystore.password	
ssl.truststore.location	
ssl.truststore.password	

Query: Is it required to include Zookeeper details as well since its require kerberos authentication. Suspecting getting this timeout issue due to Zookeeper need.
Kindly suggest...

**Comment by Nachiket90** [comment]
@ShauryaSid As error mentions, please validate functions and variables once again. You can try isolating issue by trying to run sample schema available on Github page. If that schema works then I would suggest to add your functions incrementally to see if you missed anything. If it still fails please provide detailed log here.
