### ISSUE TITLE
Serialized message throws error

### ISSUE THREAD

**Issue by D0LLAR** [GSLabDev/pepper-box#31]
build jar from   mvn clean install -Djmeter.version=3.0 -Dkafka.version=0.9.0.1

dropped it into the lib/ext of jmeter 3.0

using the jmx from the wiki  non serialized  produces kafka messages  good ( with plain Text java request and   Kafka PlainText Load Generator Config  )   Toggling off the previous elements and on the serialized and on the serialized java request and on the Kafka Serialized Load Generator Config   and trying to do 1 message I get the following in the log  ( using jdk1.8.0_171  java)

2018/06/21 04:33:00 INFO  - jmeter.engine.StandardJMeterEngine: All thread groups have been started
2018/06/21 04:33:00 INFO  - jmeter.threads.JMeterThread: Thread started: Thread Group 1-1
2018/06/21 04:33:00 ERROR - jmeter.threads.JMeterThread: Test failed! java.lang.NoClassDefFoundError: org/apache/commons/lang/StringUtils
        at com.gslab.pepper.input.SchemaParser.getProcessedSchema(SchemaParser.java:121)
        at com.gslab.pepper.input.SchemaProcessor.getSerializedMessageIterator(SchemaProcessor.java:51)
        at com.gslab.pepper.loadgen.impl.SerializedLoadGenerator.<init>(SerializedLoadGenerator.java:37)
        at com.gslab.pepper.config.serialized.SerializedConfigElement.iterationStart(SerializedConfigElement.java:51)
        at org.apache.jmeter.control.GenericController.fireIterationStart(GenericController.java:405)
        at org.apache.jmeter.control.GenericController.fireIterEvents(GenericController.java:397)

**Comment by HemantManglani** [comment]
I'm also facing exact same issue for Serialized message. Has anyone managed to find a workaround?

2018/12/07 15:57:23 ERROR - jmeter.threads.JMeterThread: Test failed! java.lang.NoClassDefFoundError: org/apache/commons/lang/StringUtils
	at com.gslab.pepper.input.SchemaParser.getProcessedSchema(SchemaParser.java:121)
	at com.gslab.pepper.input.SchemaProcessor.getSerializedMessageIterator(SchemaProcessor.java:51)
	at com.gslab.pepper.loadgen.impl.SerializedLoadGenerator.<init>(SerializedLoadGenerator.java:37)
	at com.gslab.pepper.config.serialized.SerializedConfigElement.iterationStart(SerializedConfigElement.java:51)
	at org.apache.jmeter.control.GenericController.fireIterationStart(GenericController.java:405)
	at org.apache.jmeter.control.GenericController.fireIterEvents(GenericController.java:397)
	at org.apache.jmeter.control.GenericController.next(GenericController.java:158)
	at org.apache.jmeter.control.LoopController.next(LoopController.java:123)
	at org.apache.jmeter.threads.AbstractThreadGroup.next(AbstractThreadGroup.java:87)
	at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:239)
	at java.lang.Thread.run(Thread.java:748)

**Comment by kasramp** [comment]
I have exactly the same problem with Serialized Message. I tried with Jmeter 5 and Jmeter 3.1 but none works.

**Comment by lpleo** [comment]
Hi, I have the same error. I found a workaround by copying the jar of commons-lang-2.6.jar in {jmeter-root}/lib/ext.
I had also the same problems with others libraries and I fixed it in the same way.

**Comment by madbis** [comment]
I am facing the same issue, has there been any resolution to this?

**Comment by kabya** [comment]
Hi ,was any one able to solve this issue. Please help
