### ISSUE TITLE
Jmeter trying to run Pepper-Box PlainText Config in jmeter 2.4 version

### ISSUE THREAD

**Issue by jmetertechi** [GSLabDev/pepper-box#42]
i am seeing the error in the jmeter log file for the kafka- Pepper-Box PlainText Config  plugin i m using. 

48:52 INFO  - jmeter.engine.StandardJMeterEngine: All threads have been started 
:48:52 ERROR - jmeter.testbeans.TestBeanHelper: This should never happen. com.gslab.pepper.config.plaintext.PlainTextConfigElement setGenerator 1 java.lang.String java.lang.IllegalArgumentException: argument type mismatch
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.apache.jmeter.testbeans.TestBeanHelper.invokeOrBailOut(TestBeanHelper.java:157)
	at org.apache.jmeter.testbeans.TestBeanHelper.prepare(TestBeanHelper.java:90)
	at org.apache.jmeter.threads.TestCompiler.trackIterationListeners(TestCompiler.java:140)
	at org.apache.jmeter.threads.TestCompiler.subtractNode(TestCompiler.java:110)
	at org.apache.jorphan.collections.HashTree.traverseInto(HashTree.java:992)
	at org.apache.jorphan.collections.HashTree.traverseInto(HashTree.java:989)
	at org.apache.jorphan.collections.HashTree.traverse(HashTree.java:971)
	at org.apache.jmeter.threads.JMeterThread.initRun(JMeterThread.java:449)
	at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:239)
	at java.base/java.lang.Thread.run(Thread.java:834)
:52 ERROR - jmeter.threads.JMeterThread: Test failed! java.lang.Error: java.lang.IllegalArgumentException: argument type mismatch
	at org.apache.jmeter.testbeans.TestBeanHelper.invokeOrBailOut(TestBeanHelper.java:160)
	at org.apache.jmeter.testbeans.TestBeanHelper.prepare(TestBeanHelper.java:90)
	at org.apache.jmeter.threads.TestCompiler.trackIterationListeners(TestCompiler.java:140)
	at org.apache.jmeter.threads.TestCompiler.subtractNode(TestCompiler.java:110)
	at org.apache.jorphan.collections.HashTree.traverseInto(HashTree.java:992)
	at org.apache.jorphan.collections.HashTree.traverseInto(HashTree.java:989)
	at org.apache.jorphan.collections.HashTree.traverse(HashTree.java:971)
	at org.apache.jmeter.threads.JMeterThread.initRun(JMeterThread.java:449)
	at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:239)
	at java.base/java.lang.Thread.run(Thread.java:834)
how to resolve this

**Comment by Nachiket90** [comment]
JMeter 2.4 is very old version and IMO nobody uses it anymore as version 5.x is current. We have not tested with 2.x version but I would suggest you to upgrade your JMeter to 3.x at least and then try. Please update the thread if problem persists with recommended version.

**Comment by Nachiket90** [comment]
Closing as no progress observed.
