### ISSUE TITLE
Error when start  in Jmeter windows 10

### ISSUE THREAD

**Issue by Toliar** [GSLabDev/pepper-box#43]
SEVERE: Failed to compileSchemaClass class
java.lang.NullPointerException
        at com.gslab.pepper.input.compile.InMemoryJavaCompiler.compileSchemaClass(InMemoryJavaCompiler.java:39)
        at com.gslab.pepper.input.SchemaTranslator.getPlainTextMsgIterator(SchemaTranslator.java:47)
        at com.gslab.pepper.input.SchemaProcessor.getPlainTextMessageIterator(SchemaProcessor.java:36)
        at com.gslab.pepper.loadgen.impl.PlaintTextLoadGenerator.<init>(PlaintTextLoadGenerator.java:34)
        at com.gslab.pepper.config.plaintext.PlainTextConfigElement.iterationStart(PlainTextConfigElement.java:53)
        at org.apache.jmeter.control.GenericController.fireIterationStart(GenericController.java:405)
        at org.apache.jmeter.control.GenericController.fireIterEvents(GenericController.java:397)
        at org.apache.jmeter.control.GenericController.next(GenericController.java:158)
        at org.apache.jmeter.control.LoopController.next(LoopController.java:123)
        at org.apache.jmeter.threads.AbstractThreadGroup.next(AbstractThreadGroup.java:87)
        at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:239)
        at java.lang.Thread.run(Unknown Source)

**Comment by Toliar** [comment]
Problem was in variable C:\Program Files (x86)\Common Files\Oracle\Java\javapath

**Comment by ihevcuk** [comment]
Have the same problem. Can you please describe solution in more words.

**Comment by Nachiket90** [comment]
As suggested in the document, This plugin requires JDK and not JRE and JDK should appear first on path if path env variable is being used.
