### ISSUE TITLE
NullPointerException while running a test plan with Jmeter - Version 5.1 and Kafka 2.2.0 despite the System variable only pointing JDK and not the JRE

### ISSUE THREAD

**Issue by PerfTestKafka** [GSLabDev/pepper-box#48]
NullPointerException while running a test plan with Jmeter - Version 5.1 and Kafka 2.2.0 

With previous issues, the issue was found to be resolved when the JAVA_HOME was set to be JDK instead of JRE. We have already ensured that the system variabls are only pointing to JDK and not the JRE but the issue persists.

ERROR c.g.p.l.i.PlaintTextLoadGenerator: Please make sure that expressions functions are already defined and parameters are correctly passed.
com.gslab.pepper.exception.PepperBoxException: java.lang.NullPointerException
	at com.gslab.pepper.input.SchemaTranslator.getPlainTextMsgIterator(SchemaTranslator.java:54) ~[pepper-box-1.0.jar:?]
	at com.gslab.pepper.input.SchemaProcessor.getPlainTextMessageIterator(SchemaProcessor.java:36) ~[pepper-box-1.0.jar:?]
	at com.gslab.pepper.loadgen.impl.PlaintTextLoadGenerator.<init>(PlaintTextLoadGenerator.java:34) [pepper-box-1.0.jar:?]
	at com.gslab.pepper.config.plaintext.PlainTextConfigElement.iterationStart(PlainTextConfigElement.java:53) [pepper-box-1.0.jar:?]
	at org.apache.jmeter.control.GenericController.fireIterationStart(GenericController.java:399) [ApacheJMeter_core.jar:5.1.1 r1855137]
	at org.apache.jmeter.control.GenericController.fireIterEvents(GenericController.java:391) [ApacheJMeter_core.jar:5.1.1 r1855137]
	at org.apache.jmeter.control.GenericController.next(GenericController.java:160) [ApacheJMeter_core.jar:5.1.1 r1855137]
	at org.apache.jmeter.control.LoopController.next(LoopController.java:135) [ApacheJMeter_core.jar:5.1.1 r1855137]
	at org.apache.jmeter.threads.AbstractThreadGroup.next(AbstractThreadGroup.java:87) [ApacheJMeter_core.jar:5.1.1 r1855137]
	at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:251) [ApacheJMeter_core.jar:5.1.1 r1855137]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_211]
Caused by: java.lang.NullPointerException
	at com.gslab.pepper.input.compile.InMemoryJavaCompiler.compileSchemaClass(InMemoryJavaCompiler.java:39) ~[pepper-box-1.0.jar:?]
	at com.gslab.pepper.input.SchemaTranslator.getPlainTextMsgIterator(SchemaTranslator.java:47) ~[pepper-box-1.0.jar:?]
	... 10 more

**Comment by PerfTestKafka** [comment]
Hi.We noticed that this error was only showing up in Windows. It was found that, the **jmeter.bat** in the jmeetr_home/bin folder had an explicit reference to java.exe of JRE that was over-riding the java home set up done in system variables. Defining the path as JDK java.exe solved the problem for us. Leaving the updated entry here for future reference.

if not defined JM_LAUNCH (
    set JM_LAUNCH=C:/Program Files/Java/jdk1.8.0_211/bin/java.exe
)

**Comment by PerfTestKafka** [comment]
Issue was resolved by following above steps.

**Comment by nikos** [comment]
Setting the `JM_LAUNCH` environment variable explictly to a JDK java most probably would also fix issues #30 and #49
