### ISSUE TITLE
MessageIterator1498469983691.java:1: error: constant string too long

### ISSUE THREAD

**Issue by petergdoyle** [GSLabDev/pepper-box#5]
When trying to use a 114k Json Schema Template and the "Pepper-Box Plaintext Config" I get an exception

```
2017-06-26 03:39:44,266 ERROR o.a.j.JMeter: Uncaught exception: 
java.lang.ClassFormatError: Truncated class file
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_91]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763) ~[?:1.8.0_91]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:642) ~[?:1.8.0_91]
	at com.gslab.pepper.input.compile.DynamicClassLoader.findClass(DynamicClassLoader.java:59) ~[pepper-box-1.0.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_91]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_91]
	at com.gslab.pepper.input.compile.InMemoryJavaCompiler.compileSchemaClass(InMemoryJavaCompiler.java:46) ~[pepper-box-1.0.jar:?]
	at com.gslab.pepper.input.SchemaTranslator.getPlainTextMsgIterator(SchemaTranslator.java:47) ~[pepper-box-1.0.jar:?]
	at com.gslab.pepper.input.SchemaProcessor.getPlainTextMessageIterator(SchemaProcessor.java:36) ~[pepper-box-1.0.jar:?]
	at com.gslab.pepper.loadgen.impl.PlaintTextLoadGenerator.<init>(PlaintTextLoadGenerator.java:34) ~[pepper-box-1.0.jar:?]
	at com.gslab.pepper.config.plaintext.PlainTextConfigElement.iterationStart(PlainTextConfigElement.java:53) ~[pepper-box-1.0.jar:?]
	at org.apache.jmeter.control.GenericController.fireIterationStart(GenericController.java:393) ~[ApacheJMeter_core.jar:3.2 r1790748]
	at org.apache.jmeter.control.GenericController.fireIterEvents(GenericController.java:385) ~[ApacheJMeter_core.jar:3.2 r1790748]
	at org.apache.jmeter.control.GenericController.next(GenericController.java:158) ~[ApacheJMeter_core.jar:3.2 r1790748]
	at org.apache.jmeter.control.LoopController.next(LoopController.java:123) ~[ApacheJMeter_core.jar:3.2 r1790748]
	at org.apache.jmeter.threads.AbstractThreadGroup.next(AbstractThreadGroup.java:87) ~[ApacheJMeter_core.jar:3.2 r1790748]
	at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:252) ~[ApacheJMeter_core.jar:3.2 r1790748]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
2017-06-26 03:39:44,270 INFO o.a.j.e.StandardJMeterEngine: Notifying test listeners of end of test
2017-06-26 03:39:44,270 INFO o.a.j.g.u.JMeterMenuBar: setRunning(false, *local*)
```

and the following goes to the Jmeter Console 

```
/MessageIterator1498469983691.java:1: error: constant string too long
import java.util.Iterator;import static com.gslab.pepper.input.FieldDataFunctions.*;import static com.gslab.pepper.input.CustomFunctions.*;public class MessageIterator1498469983691
...
```

maybe this is an issue with InMemoryJavaCompiler but that isn't that large a message especially when trying to test larger messages. 

any thoughts would be appreciated before I start digging through source code. 

thank you

**Comment by satishbhor** [comment]
Hey thanks for filing bug. We are dynamically translating template into series of java statements. hence it is consequence of this either translated class(MessageIterator1498469983691) statement is too long or some constant is too long in that class thats why JAVA compiler API complaining. But we are checking/fixing this and code base will be updated with fix within a day.   

Thanks again for sharing issue.

**Comment by petergdoyle** [comment]
Yes the approach taken to build a java class using the contents of the Kafka message and apparently declare a constant has hit a limit in terms of Java the way it is coded. 

Any thoughts about refactoring to load this value into a memory Buffer rather than building a String? 

[http://howtodoinjava.com/java-7/nio/java-nio-2-0-working-with-buffers/](http://howtodoinjava.com/java-7/nio/java-nio-2-0-working-with-buffers/)

it seems like a great plugin and much needed.

**Comment by petergdoyle** [comment]
Here is the result of one of the messages I am trying to load when it is trying dynamically create the class: 
https://gist.github.com/petergdoyle/afa447290ff591de5fb11cfd6fb63099 

Maybe even try to optimize the initialization of the StringBuilder and break it into chunks and you might get away with it. Still think you might want to keep it in pre-allocated memory but I haven't dug too deep into the code.

Thanks for your quick response.

**Comment by satishbhor** [comment]
Thanks for your valuable suggestions, while using string there was no as such thing in mind and our templates were small. But we will take it consideration for optimizations. We will first fix large statement issue and then will go for enhancing preallocated memory implementation. 

If you like to contribute to enhance code you are always welcome.

**Comment by satishbhor** [comment]
@petergdoyle Pushed fix for this, Could you please verify ?
