### ISSUE TITLE
pepperbox jar file for Jmeter version =5 and Kafka version=0.10.2.1

### ISSUE THREAD

**Issue by sowjanyau** [GSLabDev/pepper-box#50]
Hi im looking for pepperbox  jarfile which supports jmeter 5

**Comment by sowjanyau** [comment]
I have tried with jmeter5.0_kafka1.1.0 still im getting below error.
Can you please help me to resolve this issue

2019-07-30 15:56:15,147 INFO o.a.j.e.StandardJMeterEngine: Running the test!
2019-07-30 15:56:15,147 INFO o.a.j.s.SampleEvent: List of sample_variables: []
2019-07-30 15:56:15,147 INFO o.a.j.p.j.t.JavaTest: Created class: com.gslab.pepper.sampler.PepperBoxKafkaSampler. Uses tearDownTest: true
2019-07-30 15:56:15,147 INFO o.a.j.g.u.JMeterMenuBar: setRunning(true, *local*)
2019-07-30 15:56:15,382 INFO o.a.j.e.StandardJMeterEngine: Starting ThreadGroup: 1 : Thread Group
2019-07-30 15:56:15,382 INFO o.a.j.e.StandardJMeterEngine: Starting 1 threads for group Thread Group.
2019-07-30 15:56:15,382 INFO o.a.j.e.StandardJMeterEngine: Thread will continue on error
2019-07-30 15:56:15,382 INFO o.a.j.t.ThreadGroup: Starting thread group... number=1 threads=1 ramp-up=1 perThread=1000.0 delayedStart=false
2019-07-30 15:56:15,382 INFO o.a.j.t.ThreadGroup: Started thread group number 1
2019-07-30 15:56:15,382 INFO o.a.j.e.StandardJMeterEngine: All thread groups have been started
2019-07-30 15:56:15,382 INFO o.a.j.t.JMeterThread: Thread started: Thread Group 1-1
2019-07-30 15:56:15,491 INFO o.a.k.c.p.ProducerConfig: ProducerConfig values: 
	compression.type = none
	metric.reporters = []
	metadata.max.age.ms = 300000
	metadata.fetch.timeout.ms = 60000
	reconnect.backoff.ms = 50
	sasl.kerberos.ticket.renew.window.factor = 0.8
	bootstrap.servers = [10.144.101.85:9093]
	retry.backoff.ms = 100
	sasl.kerberos.kinit.cmd = /usr/bin/kinit
	buffer.memory = 33554432
	timeout.ms = 30000
	key.serializer = class org.apache.kafka.common.serialization.StringSerializer
	sasl.kerberos.service.name = null
	sasl.kerberos.ticket.renew.jitter = 0.05
	ssl.keystore.type = JKS
	ssl.trustmanager.algorithm = PKIX
	block.on.buffer.full = false
	ssl.key.password = null
	max.block.ms = 60000
	sasl.kerberos.min.time.before.relogin = 60000
	connections.max.idle.ms = 540000
	ssl.truststore.password = null
	max.in.flight.requests.per.connection = 5
	metrics.num.samples = 2
	client.id = 
	ssl.endpoint.identification.algorithm = null
	ssl.protocol = TLS
	request.timeout.ms = 30000
	ssl.provider = null
	ssl.enabled.protocols = [TLSv1.2, TLSv1.1, TLSv1]
	acks = 1
	batch.size = 16384
	ssl.keystore.location = null
	receive.buffer.bytes = 32768
	ssl.cipher.suites = null
	ssl.truststore.type = JKS
	security.protocol = SASL_SSL
	retries = 0
	max.request.size = 1048576
	value.serializer = class org.apache.kafka.common.serialization.StringSerializer
	ssl.truststore.location = null
	ssl.keystore.password = null
	ssl.keymanager.algorithm = SunX509
	metrics.sample.window.ms = 30000
	partitioner.class = class org.apache.kafka.clients.producer.internals.DefaultPartitioner
	send.buffer.bytes = 131072
	linger.ms = 0

2019-07-30 15:56:15,491 INFO o.a.k.c.p.KafkaProducer: Closing the Kafka producer with timeoutMillis = 0 ms.
2019-07-30 15:56:15,491 ERROR o.a.j.t.JMeterThread: Error while processing sampler: 'Java Request'.
org.apache.kafka.common.KafkaException: Failed to construct kafka producer
	at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:321) ~[pepper-box-mas-1.0.jar:?]
	at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:181) ~[pepper-box-mas-1.0.jar:?]
	at com.gslab.pepper.sampler.PepperBoxKafkaSampler.setupTest(PepperBoxKafkaSampler.java:150) ~[pepper-box-mas-1.0.jar:?]
	at org.apache.jmeter.protocol.java.sampler.JavaSampler.sample(JavaSampler.java:194) ~[ApacheJMeter_java.jar:5.0 r1840935]
	at org.apache.jmeter.threads.JMeterThread.doSampling(JMeterThread.java:622) ~[ApacheJMeter_core.jar:5.0 r1840935]
	at org.apache.jmeter.threads.JMeterThread.executeSamplePackage(JMeterThread.java:546) ~[ApacheJMeter_core.jar:5.0 r1840935]
	at org.apache.jmeter.threads.JMeterThread.processSampler(JMeterThread.java:486) [ApacheJMeter_core.jar:5.0 r1840935]
	at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:253) [ApacheJMeter_core.jar:5.0 r1840935]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
Caused by: org.apache.kafka.common.KafkaException: java.lang.SecurityException: java.io.IOException: Configuration Error:
	Line 2: expected [{], found [org.apache.kafka.common.security.plain.PlainLoginModule]
	at org.apache.kafka.common.network.SaslChannelBuilder.configure(SaslChannelBuilder.java:74) ~[pepper-box-mas-1.0.jar:?]
	at org.apache.kafka.common.network.ChannelBuilders.create(ChannelBuilders.java:60) ~[pepper-box-mas-1.0.jar:?]
	at org.apache.kafka.clients.ClientUtils.createChannelBuilder(ClientUtils.java:79) ~[pepper-box-mas-1.0.jar:?]
	at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:271) ~[pepper-box-mas-1.0.jar:?]
	... 8 more
Caused by: java.lang.SecurityException: java.io.IOException: Configuration Error:
	Line 2: expected [{], found [org.apache.kafka.common.security.plain.PlainLoginModule]
	at sun.security.provider.ConfigFile$Spi.<init>(ConfigFile.java:137) ~[?:1.8.0_191]
	at sun.security.provider.ConfigFile.<init>(ConfigFile.java:102) ~[?:1.8.0_191]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_191]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_191]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_191]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_191]
	at java.lang.Class.newInstance(Class.java:442) ~[?:1.8.0_191]
	at javax.security.auth.login.Configuration$2.run(Configuration.java:255) ~[?:1.8.0_191]
	at javax.security.auth.login.Configuration$2.run(Configuration.java:247) ~[?:1.8.0_191]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_191]
	at javax.security.auth.login.Configuration.getConfiguration(Configuration.java:246) ~[?:1.8.0_191]
	at org.apache.kafka.common.security.kerberos.Login.login(Login.java:291) ~[pepper-box-mas-1.0.jar:?]
	at org.apache.kafka.common.security.kerberos.Login.<init>(Login.java:104) ~[pepper-box-mas-1.0.jar:?]
	at org.apache.kafka.common.security.kerberos.LoginManager.<init>(LoginManager.java:44) ~[pepper-box-mas-1.0.jar:?]
	at org.apache.kafka.common.security.kerberos.LoginManager.acquireLoginManager(LoginManager.java:85) ~[pepper-box-mas-1.0.jar:?]
	at org.apache.kafka.common.network.SaslChannelBuilder.configure(SaslChannelBuilder.java:55) ~[pepper-box-mas-1.0.jar:?]
	at org.apache.kafka.common.network.ChannelBuilders.create(ChannelBuilders.java:60) ~[pepper-box-mas-1.0.jar:?]
	at org.apache.kafka.clients.ClientUtils.createChannelBuilder(ClientUtils.java:79) ~[pepper-box-mas-1.0.jar:?]
	at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:271) ~[pepper-box-mas-1.0.jar:?]
	... 8 more
Caused by: java.io.IOException: Configuration Error:
	Line 2: expected [{], found [org.apache.kafka.common.security.plain.PlainLoginModule]
	at sun.security.provider.ConfigFile$Spi.ioException(ConfigFile.java:666) ~[?:1.8.0_191]
	at sun.security.provider.ConfigFile$Spi.match(ConfigFile.java:532) ~[?:1.8.0_191]
	at sun.security.provider.ConfigFile$Spi.parseLoginEntry(ConfigFile.java:445) ~[?:1.8.0_191]
	at sun.security.provider.ConfigFile$Spi.readConfig(ConfigFile.java:427) ~[?:1.8.0_191]
	at sun.security.provider.ConfigFile$Spi.init(ConfigFile.java:329) ~[?:1.8.0_191]
	at sun.security.provider.ConfigFile$Spi.init(ConfigFile.java:271) ~[?:1.8.0_191]
	at sun.security.provider.ConfigFile$Spi.<init>(ConfigFile.java:135) ~[?:1.8.0_191]
	at sun.security.provider.ConfigFile.<init>(ConfigFile.java:102) ~[?:1.8.0_191]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_191]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_191]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_191]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_191]
	at java.lang.Class.newInstance(Class.java:442) ~[?:1.8.0_191]
	at javax.security.auth.login.Configuration$2.run(Configuration.java:255) ~[?:1.8.0_191]
	at javax.security.auth.login.Configuration$2.run(Configuration.java:247) ~[?:1.8.0_191]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_191]
	at javax.security.auth.login.Configuration.getConfiguration(Configuration.java:246) ~[?:1.8.0_191]
	at org.apache.kafka.common.security.kerberos.Login.login(Login.java:291) ~[pepper-box-mas-1.0.jar:?]
	at org.apache.kafka.common.security.kerberos.Login.<init>(Login.java:104) ~[pepper-box-mas-1.0.jar:?]
	at org.apache.kafka.common.security.kerberos.LoginManager.<init>(LoginManager.java:44) ~[pepper-box-mas-1.0.jar:?]
	at org.apache.kafka.common.security.kerberos.LoginManager.acquireLoginManager(LoginManager.java:85) ~[pepper-box-mas-1.0.jar:?]
	at org.apache.kafka.common.network.SaslChannelBuilder.configure(SaslChannelBuilder.java:55) ~[pepper-box-mas-1.0.jar:?]
	at org.apache.kafka.common.network.ChannelBuilders.create(ChannelBuilders.java:60) ~[pepper-box-mas-1.0.jar:?]
	at org.apache.kafka.clients.ClientUtils.createChannelBuilder(ClientUtils.java:79) ~[pepper-box-mas-1.0.jar:?]
	at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:271) ~[pepper-box-mas-1.0.jar:?]
	... 8 more
2019-07-30 15:56:15,491 INFO o.a.j.t.JMeterThread: Thread is done: Thread Group 1-1
2019-07-30 15:56:15,491 INFO o.a.j.t.JMeterThread: Thread finished: Thread Group 1-1
2019-07-30 15:56:15,491 INFO o.a.j.e.StandardJMeterEngine: Notifying test listeners of end of test
2019-07-30 15:56:15,491 WARN o.a.j.e.StandardJMeterEngine: Error encountered during shutdown of org.apache.jmeter.protocol.java.sampler.JavaSampler@46aafe4b
java.lang.NullPointerException: null
	at com.gslab.pepper.sampler.PepperBoxKafkaSampler.teardownTest(PepperBoxKafkaSampler.java:193) ~[pepper-box-mas-1.0.jar:?]
	at org.apache.jmeter.protocol.java.sampler.JavaSampler.testEnded(JavaSampler.java:293) ~[ApacheJMeter_java.jar:5.0 r1840935]
	at org.apache.jmeter.engine.StandardJMeterEngine.notifyTestListenersOfEnd(StandardJMeterEngine.java:227) [ApacheJMeter_core.jar:5.0 r1840935]
	at org.apache.jmeter.engine.StandardJMeterEngine.run(StandardJMeterEngine.java:495) [ApacheJMeter_core.jar:5.0 r1840935]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
2019-07-30 15:56:15,491 INFO o.a.j.g.u.JMeterMenuBar: setRunning(false, *local*)

**Comment by Nachiket90** [comment]
Can you try with kafka 1.1 if its possible to upgrade your kafka deployment?
If not you can try to build code with JMeter 5 and kafka 0.10.* version and submit a PR as currently we have not supported that combination

**Comment by nikunjrathi** [comment]
Hello @Nachiket90 , 
i am using Kafka kafka_2.12-2.4.0 along with jmeter 5.0 , still facing the error.. The error log is as follows .. can you guide, how can this be resolved ?

_2020-01-09 14:40:44,037 INFO o.a.j.e.StandardJMeterEngine: Running the test!
2020-01-09 14:40:44,038 INFO o.a.j.s.SampleEvent: List of sample_variables: []
2020-01-09 14:40:44,038 INFO o.a.j.p.j.t.JavaTest: Created class: com.gslab.pepper.sampler.PepperBoxKafkaSampler. Uses tearDownTest: true
2020-01-09 14:40:44,038 INFO o.a.j.g.u.JMeterMenuBar: setRunning(true, *local*)
2020-01-09 14:40:44,111 INFO o.a.j.e.StandardJMeterEngine: Starting ThreadGroup: 1 : Thread Group
2020-01-09 14:40:44,111 INFO o.a.j.e.StandardJMeterEngine: Starting 1 threads for group Thread Group.
2020-01-09 14:40:44,111 INFO o.a.j.e.StandardJMeterEngine: Thread will continue on error
2020-01-09 14:40:44,111 INFO o.a.j.t.ThreadGroup: Starting thread group... number=1 threads=1 ramp-up=1 perThread=1000.0 delayedStart=false
2020-01-09 14:40:44,116 INFO o.a.j.t.ThreadGroup: Started thread group number 1
2020-01-09 14:40:44,116 INFO o.a.j.e.StandardJMeterEngine: All thread groups have been started
2020-01-09 14:40:44,116 INFO o.a.j.t.JMeterThread: Thread started: Thread Group 1-1
2020-01-09 14:40:44,399 INFO o.a.k.c.p.ProducerConfig: ProducerConfig values: 
	compression.type = none
	metric.reporters = []
	metadata.max.age.ms = 300000
	metadata.fetch.timeout.ms = 60000
	reconnect.backoff.ms = 50
	sasl.kerberos.ticket.renew.window.factor = 0.8
	bootstrap.servers = [<bootstrap server name>:6667]
	retry.backoff.ms = 100
	sasl.kerberos.kinit.cmd = /usr/bin/kinit
	buffer.memory = 33554432
	timeout.ms = 30000
	key.serializer = class org.apache.kafka.common.serialization.StringSerializer
	sasl.kerberos.service.name = kafka
	sasl.kerberos.ticket.renew.jitter = 0.05
	ssl.keystore.type = JKS
	ssl.trustmanager.algorithm = PKIX
	block.on.buffer.full = false
	ssl.key.password = null
	max.block.ms = 60000
	sasl.kerberos.min.time.before.relogin = 60000
	connections.max.idle.ms = 540000
	ssl.truststore.password = null
	max.in.flight.requests.per.connection = 5
	metrics.num.samples = 2
	client.id = 
	ssl.endpoint.identification.algorithm = null
	ssl.protocol = TLS
	request.timeout.ms = 30000
	ssl.provider = null
	ssl.enabled.protocols = [TLSv1.2, TLSv1.1, TLSv1]
	acks = 1
	batch.size = 16384
	ssl.keystore.location = null
	receive.buffer.bytes = 32768
	ssl.cipher.suites = null
	ssl.truststore.type = JKS
	security.protocol = SASL_SSL
	retries = 0
	max.request.size = 1048576
	value.serializer = class org.apache.kafka.common.serialization.StringSerializer
	ssl.truststore.location = null
	ssl.keystore.password = null
	ssl.keymanager.algorithm = SunX509
	metrics.sample.window.ms = 30000
	partitioner.class = class org.apache.kafka.clients.producer.internals.DefaultPartitioner
	send.buffer.bytes = 131072
	linger.ms = 0

2020-01-09 14:40:44,405 INFO o.a.k.c.p.KafkaProducer: Closing the Kafka producer with timeoutMillis = 0 ms.
2020-01-09 14:40:44,405 ERROR o.a.j.t.JMeterThread: Error while processing sampler: 'Java Request'.
org.apache.kafka.common.KafkaException: Failed to construct kafka producer
	at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:321) ~[pepper-box-1.0.jar:?]
	at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:181) ~[pepper-box-1.0.jar:?]
	at com.gslab.pepper.sampler.PepperBoxKafkaSampler.setupTest(PepperBoxKafkaSampler.java:116) ~[pepper-box-1.0.jar:?]
	at org.apache.jmeter.protocol.java.sampler.JavaSampler.sample(JavaSampler.java:194) ~[ApacheJMeter_java.jar:5.0 r1840935]
	at org.apache.jmeter.threads.JMeterThread.doSampling(JMeterThread.java:622) ~[ApacheJMeter_core.jar:5.0 r1840935]
	at org.apache.jmeter.threads.JMeterThread.executeSamplePackage(JMeterThread.java:546) ~[ApacheJMeter_core.jar:5.0 r1840935]
	at org.apache.jmeter.threads.JMeterThread.processSampler(JMeterThread.java:486) [ApacheJMeter_core.jar:5.0 r1840935]
	at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:253) [ApacheJMeter_core.jar:5.0 r1840935]
	at java.lang.Thread.run(Thread.java:830) [?:?]
Caused by: org.apache.kafka.common.KafkaException: java.lang.SecurityException: java.io.IOException: Configuration Error:
	Line 1: expected [{], found [<default Realm>]
	at org.apache.kafka.common.network.SaslChannelBuilder.configure(SaslChannelBuilder.java:74) ~[pepper-box-1.0.jar:?]
	at org.apache.kafka.common.network.ChannelBuilders.create(ChannelBuilders.java:60) ~[pepper-box-1.0.jar:?]
	at org.apache.kafka.clients.ClientUtils.createChannelBuilder(ClientUtils.java:79) ~[pepper-box-1.0.jar:?]
	at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:271) ~[pepper-box-1.0.jar:?]
	... 8 more
Caused by: java.lang.SecurityException: java.io.IOException: Configuration Error:
	Line 1: expected [{], found [<default Realm>]
	at sun.security.provider.ConfigFile$Spi.<init>(ConfigFile.java:137) ~[?:?]
	at sun.security.provider.ConfigFile.<init>(ConfigFile.java:102) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500) ~[?:?]
	at java.lang.reflect.ReflectAccess.newInstance(ReflectAccess.java:166) ~[?:?]
	at jdk.internal.reflect.ReflectionFactory.newInstance(ReflectionFactory.java:404) ~[?:?]
	at java.lang.Class.newInstance(Class.java:591) ~[?:?]
	at javax.security.auth.login.Configuration$2.run(Configuration.java:255) ~[?:?]
	at javax.security.auth.login.Configuration$2.run(Configuration.java:246) ~[?:?]
	at java.security.AccessController.doPrivileged(AccessController.java:554) ~[?:?]
	at javax.security.auth.login.Configuration.getConfiguration(Configuration.java:245) ~[?:?]
	at org.apache.kafka.common.security.kerberos.Login.login(Login.java:291) ~[pepper-box-1.0.jar:?]
	at org.apache.kafka.common.security.kerberos.Login.<init>(Login.java:104) ~[pepper-box-1.0.jar:?]
	at org.apache.kafka.common.security.kerberos.LoginManager.<init>(LoginManager.java:44) ~[pepper-box-1.0.jar:?]
	at org.apache.kafka.common.security.kerberos.LoginManager.acquireLoginManager(LoginManager.java:85) ~[pepper-box-1.0.jar:?]
	at org.apache.kafka.common.network.SaslChannelBuilder.configure(SaslChannelBuilder.java:55) ~[pepper-box-1.0.jar:?]
	at org.apache.kafka.common.network.ChannelBuilders.create(ChannelBuilders.java:60) ~[pepper-box-1.0.jar:?]
	at org.apache.kafka.clients.ClientUtils.createChannelBuilder(ClientUtils.java:79) ~[pepper-box-1.0.jar:?]
	at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:271) ~[pepper-box-1.0.jar:?]
	... 8 more
Caused by: java.io.IOException: Configuration Error:
	Line 1: expected [{], found [<default Realm>]
	at sun.security.provider.ConfigFile$Spi.ioException(ConfigFile.java:665) ~[?:?]
	at sun.security.provider.ConfigFile$Spi.match(ConfigFile.java:531) ~[?:?]
	at sun.security.provider.ConfigFile$Spi.parseLoginEntry(ConfigFile.java:444) ~[?:?]
	at sun.security.provider.ConfigFile$Spi.readConfig(ConfigFile.java:426) ~[?:?]
	at sun.security.provider.ConfigFile$Spi.init(ConfigFile.java:329) ~[?:?]
	at sun.security.provider.ConfigFile$Spi.init(ConfigFile.java:271) ~[?:?]
	at sun.security.provider.ConfigFile$Spi.<init>(ConfigFile.java:135) ~[?:?]
	at sun.security.provider.ConfigFile.<init>(ConfigFile.java:102) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500) ~[?:?]
	at java.lang.reflect.ReflectAccess.newInstance(ReflectAccess.java:166) ~[?:?]
	at jdk.internal.reflect.ReflectionFactory.newInstance(ReflectionFactory.java:404) ~[?:?]
	at java.lang.Class.newInstance(Class.java:591) ~[?:?]
	at javax.security.auth.login.Configuration$2.run(Configuration.java:255) ~[?:?]
	at javax.security.auth.login.Configuration$2.run(Configuration.java:246) ~[?:?]
	at java.security.AccessController.doPrivileged(AccessController.java:554) ~[?:?]
	at javax.security.auth.login.Configuration.getConfiguration(Configuration.java:245) ~[?:?]
	at org.apache.kafka.common.security.kerberos.Login.login(Login.java:291) ~[pepper-box-1.0.jar:?]
	at org.apache.kafka.common.security.kerberos.Login.<init>(Login.java:104) ~[pepper-box-1.0.jar:?]
	at org.apache.kafka.common.security.kerberos.LoginManager.<init>(LoginManager.java:44) ~[pepper-box-1.0.jar:?]
	at org.apache.kafka.common.security.kerberos.LoginManager.acquireLoginManager(LoginManager.java:85) ~[pepper-box-1.0.jar:?]
	at org.apache.kafka.common.network.SaslChannelBuilder.configure(SaslChannelBuilder.java:55) ~[pepper-box-1.0.jar:?]
	at org.apache.kafka.common.network.ChannelBuilders.create(ChannelBuilders.java:60) ~[pepper-box-1.0.jar:?]
	at org.apache.kafka.clients.ClientUtils.createChannelBuilder(ClientUtils.java:79) ~[pepper-box-1.0.jar:?]
	at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:271) ~[pepper-box-1.0.jar:?]
	... 8 more
2020-01-09 14:40:44,406 INFO o.a.j.t.JMeterThread: Thread is done: Thread Group 1-1
2020-01-09 14:40:44,406 INFO o.a.j.t.JMeterThread: Thread finished: Thread Group 1-1
2020-01-09 14:40:44,406 INFO o.a.j.e.StandardJMeterEngine: Notifying test listeners of end of test
2020-01-09 14:40:44,406 WARN o.a.j.e.StandardJMeterEngine: Error encountered during shutdown of org.apache.jmeter.protocol.java.sampler.JavaSampler@2fa5add1
java.lang.NullPointerException: null
	at com.gslab.pepper.sampler.PepperBoxKafkaSampler.teardownTest(PepperBoxKafkaSampler.java:155) ~[pepper-box-1.0.jar:?]
	at org.apache.jmeter.protocol.java.sampler.JavaSampler.testEnded(JavaSampler.java:293) ~[ApacheJMeter_java.jar:5.0 r1840935]
	at org.apache.jmeter.engine.StandardJMeterEngine.notifyTestListenersOfEnd(StandardJMeterEngine.java:227) [ApacheJMeter_core.jar:5.0 r1840935]
	at org.apache.jmeter.engine.StandardJMeterEngine.run(StandardJMeterEngine.java:495) [ApacheJMeter_core.jar:5.0 r1840935]
	at java.lang.Thread.run(Thread.java:830) [?:?]
2020-01-09 14:40:44,406 INFO o.a.j.g.u.JMeterMenuBar: setRunning(false, *local*)_


thanks
nikunj
