### ISSUE TITLE
ERROR c.g.p.l.i.PlaintTextLoadGenerator: Please make sure that expressions functions are already defined and parameters are correctly passed. com.gslab.pepper.exception.PepperBoxException: java.lang.NullPointerException.  JDK is mentioned in path, have also modified JM_Launch

### ISSUE THREAD

**Issue by clairemcgonagle** [GSLabDev/pepper-box#70]
Hi Everyone
I've looked at #48, #49 and #30.  I'm still getting this issue.
My Path has the JDK/

C:\Users\Administrator>PATH
PATH=C:\Program Files\Java\jdk1.8.0_281\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files\Amazon\cfn-bootstrap\;C:\Users\Administrator\AppData\Local\Microsoft\WindowsApps;

I modified the JM_launch in jmeter.bat also.  Has anyone got any other ideas on what could be wrong here?
Many Thanks

2021-03-24 16:21:36,609 ERROR c.g.p.l.i.PlaintTextLoadGenerator: Please make sure that expressions functions are already defined and parameters are correctly passed.
com.gslab.pepper.exception.PepperBoxException: java.lang.NullPointerException
	at com.gslab.pepper.input.SchemaTranslator.getPlainTextMsgIterator(SchemaTranslator.java:54) ~[pepper-box-1.0.jar:?]
	at com.gslab.pepper.input.SchemaProcessor.getPlainTextMessageIterator(SchemaProcessor.java:36) ~[pepper-box-1.0.jar:?]
	at com.gslab.pepper.loadgen.impl.PlaintTextLoadGenerator.<init>(PlaintTextLoadGenerator.java:34) [pepper-box-1.0.jar:?]
	at com.gslab.pepper.config.plaintext.PlainTextConfigElement.iterationStart(PlainTextConfigElement.java:53) [pepper-box-1.0.jar:?]
	at org.apache.jmeter.control.GenericController.fireIterationStart(GenericController.java:399) [ApacheJMeter_core.jar:5.4.1]
	at org.apache.jmeter.control.GenericController.fireIterEvents(GenericController.java:391) [ApacheJMeter_core.jar:5.4.1]
	at org.apache.jmeter.control.GenericController.next(GenericController.java:160) [ApacheJMeter_core.jar:5.4.1]
	at org.apache.jmeter.control.LoopController.next(LoopController.java:134) [ApacheJMeter_core.jar:5.4.1]
	at org.apache.jmeter.threads.AbstractThreadGroup.next(AbstractThreadGroup.java:91) [ApacheJMeter_core.jar:5.4.1]
	at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:254) [ApacheJMeter_core.jar:5.4.1]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_281]
Caused by: java.lang.NullPointerException
	at com.gslab.pepper.input.compile.InMemoryJavaCompiler.compileSchemaClass(InMemoryJavaCompiler.java:39) ~[pepper-box-1.0.jar:?]
	at com.gslab.pepper.input.SchemaTranslator.getPlainTextMsgIterator(SchemaTranslator.java:47) ~[pepper-box-1.0.jar:?]
	... 10 more
2021-03-24 16:21:36,625 ERROR c.g.p.c.p.PlainTextConfigElement: Failed to create PlaintTextLoadGenerator instance
com.gslab.pepper.exception.PepperBoxException: com.gslab.pepper.exception.PepperBoxException: java.lang.NullPointerException
	at com.gslab.pepper.loadgen.impl.PlaintTextLoadGenerator.<init>(PlaintTextLoadGenerator.java:37) ~[pepper-box-1.0.jar:?]
	at com.gslab.pepper.config.plaintext.PlainTextConfigElement.iterationStart(PlainTextConfigElement.java:53) [pepper-box-1.0.jar:?]
	at org.apache.jmeter.control.GenericController.fireIterationStart(GenericController.java:399) [ApacheJMeter_core.jar:5.4.1]
	at org.apache.jmeter.control.GenericController.fireIterEvents(GenericController.java:391) [ApacheJMeter_core.jar:5.4.1]
	at org.apache.jmeter.control.GenericController.next(GenericController.java:160) [ApacheJMeter_core.jar:5.4.1]
	at org.apache.jmeter.control.LoopController.next(LoopController.java:134) [ApacheJMeter_core.jar:5.4.1]
	at org.apache.jmeter.threads.AbstractThreadGroup.next(AbstractThreadGroup.java:91) [ApacheJMeter_core.jar:5.4.1]
	at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:254) [ApacheJMeter_core.jar:5.4.1]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_281]
Caused by: com.gslab.pepper.exception.PepperBoxException: java.lang.NullPointerException
	at com.gslab.pepper.input.SchemaTranslator.getPlainTextMsgIterator(SchemaTranslator.java:54) ~[pepper-box-1.0.jar:?]
	at com.gslab.pepper.input.SchemaProcessor.getPlainTextMessageIterator(SchemaProcessor.java:36) ~[pepper-box-1.0.jar:?]
	at com.gslab.pepper.loadgen.impl.PlaintTextLoadGenerator.<init>(PlaintTextLoadGenerator.java:34) ~[pepper-box-1.0.jar:?]
	... 8 more
Caused by: java.lang.NullPointerException
	at com.gslab.pepper.input.compile.InMemoryJavaCompiler.compileSchemaClass(InMemoryJavaCompiler.java:39) ~[pepper-box-1.0.jar:?]
	at com.gslab.pepper.input.SchemaTranslator.getPlainTextMsgIterator(SchemaTranslator.java:47) ~[pepper-box-1.0.jar:?]
	at com.gslab.pepper.input.SchemaProcessor.getPlainTextMessageIterator(SchemaProcessor.java:36) ~[pepper-box-1.0.jar:?]
	at com.gslab.pepper.loadgen.impl.PlaintTextLoadGenerator.<init>(PlaintTextLoadGenerator.java:34) ~[pepper-box-1.0.jar:?]
	... 8 more
2021-03-24 16:21:36,625 ERROR o.a.j.t.JMeterThread: Test failed!
java.lang.NullPointerException: null
	at com.gslab.pepper.config.plaintext.PlainTextConfigElement.iterationStart(PlainTextConfigElement.java:63) ~[pepper-box-1.0.jar:?]
	at org.apache.jmeter.control.GenericController.fireIterationStart(GenericController.java:399) ~[ApacheJMeter_core.jar:5.4.1]
	at org.apache.jmeter.control.GenericController.fireIterEvents(GenericController.java:391) ~[ApacheJMeter_core.jar:5.4.1]
	at org.apache.jmeter.control.GenericController.next(GenericController.java:160) ~[ApacheJMeter_core.jar:5.4.1]
	at org.apache.jmeter.control.LoopController.next(LoopController.java:134) ~[ApacheJMeter_core.jar:5.4.1]
	at org.apache.jmeter.threads.AbstractThreadGroup.next(AbstractThreadGroup.java:91) ~[ApacheJMeter_core.jar:5.4.1]
	at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:254) [ApacheJMeter_core.jar:5.4.1]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_281]
2021-03-24 16:21:36,625 INFO o.a.j.t.JMeterThread: Thread finished: Thread Group 1-1
2021-03-24 16:21:36,625 INFO o.a.j.e.StandardJMeterEngine: Notifying test listeners of end of test
2021-03-24 16:21:36,625 INFO o.a.j.g.u.JMeterMenuBar: setRunning(false, *local*)

**Comment by clairemcgonagle** [comment]
https://www.blazemeter.com/blog/apache-kafka-how-to-load-test-with-jmeter
Resolved the issue by starting jmeter from the jmeter.bat file.  I had the jdk in PATH and in JAVA_HOME, but starting from .bat file now gets me past his issue.
