### ISSUE TITLE
Error InMemoryJavaCompiler

### ISSUE THREAD

**Issue by MasterMartbob** [GSLabDev/pepper-box#8]
I have been using pepperbox on my workstation (Windows10) without issues. Now I was ready to move the JMeter test to a test server witch is Windows 2012 R2.
I have copied everything I needed on the server and installed jdk 1.8 (jdk-8u161-windows-x64). I created the JAVA_HOME env variable and adding it to PATH with \bin
Now when I run my test in jmeter on the sever I get this error.

Feb 01, 2018 2:22:28 PM com.gslab.pepper.input.SchemaTranslator getPlainTextMsgIterator
SEVERE: Failed to compileSchemaClass classjava.lang.NullPointerException
        at com.gslab.pepper.input.compile.InMemoryJavaCompiler.compileSchemaClass(InMemoryJavaCompiler.java:39)
        at com.gslab.pepper.input.SchemaTranslator.getPlainTextMsgIterator(SchemaTranslator.java:47)
        at com.gslab.pepper.input.SchemaProcessor.getPlainTextMessageIterator(SchemaProcessor.java:36)
        at com.gslab.pepper.loadgen.impl.PlaintTextLoadGenerator.<init>(PlaintTextLoadGenerator.java:34)
        at com.gslab.pepper.config.plaintext.PlainTextConfigElement.iterationStart(PlainTextConfigElement.java:53)
        at org.apache.jmeter.control.GenericController.fireIterationStart(GenericController.java:393)
        at org.apache.jmeter.control.GenericController.fireIterEvents(GenericController.java:385)
        at org.apache.jmeter.control.GenericController.next(GenericController.java:158)
        at org.apache.jmeter.control.LoopController.next(LoopController.java:123)
        at org.apache.jmeter.threads.AbstractThreadGroup.next(AbstractThreadGroup.java:87)
        at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:253)
        at java.lang.Thread.run(Unknown Source)
		
I see that this points out to this returning NULL I think
//Custom file manager takes source code object and classloader
        ExtendedStandardJavaFileManager fileManager = new ExtendedStandardJavaFileManager(compiler.getStandardFileManager(null, null, null), compiledCode, dynamicClassLoader);
				
I run the jmeter with administrator privilege. I tried a lot of things. Do you have any ideas what that error might be.

**Comment by satishbhor** [comment]
Looks like its picking java from JRE instead of JDK
what is output of this command on test server `where java` ?  
Now days windows comes with default jre, just make sure its  picking correct JDK and not JRE

**Comment by MasterMartbob** [comment]
Yes you got it!

There was a default JRE installed on the server. I had to remove the path from the PATH env variable.

Thanks
